include:
  - volumes.yml
  - networks.yml
  - secrets.yml

services:
  mongo:
    # https://hub.docker.com/_/mongo
    image: mongo:8.2
    container_name: fastnetmon_mongo
    networks:
      - fastnetmon-network
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    secrets:
      - mongo_password
    environment:
      MONGO_INITDB_ROOT_USERNAME: administrator
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password

  # docker-compose run --rm fastnetmon fcli create_configuration
  fastnetmon:
    image: fastnetmonltd/fastnetmon-advanced:latest
    container_name: fastnetmon
    restart: unless-stopped
    networks:
      - fastnetmon-network
    secrets:
      - source: mongo_password
        target: /etc/fastnetmon/keychain/.mongo_fastnetmon_password
    cap_add:
      - NET_ADMIN
      - CAP_IPC_LOCK
    depends_on:
      - mongo
    environment:
      MONGO_USERNAME: administrator
      MONGO_HOST: mongo
      FNM_ARGS: --log_to_console
    volumes:
      - fastnetmon_logs:/var/log/fastnetmon/
      - ${FNM_PATH}/services/fastnetmon/custom-entry.sh:/custom-entry.sh:ro
      - ${FNM_PATH}/seeds/fastnetmon/:/etc/fasetnetmon/
    ports:
      - 6343:6343/udp
      - 2055:2055/udp
    entrypoint: [ "/bin/bash", "/custom-entry.sh" ]
  clickhouse:
    # https://hub.docker.com/_/clickhouse
    image: clickhouse:26.3
    profiles:
      - storage
      - visual
    container_name: clickhouse
    restart: unless-stopped
    networks:
      - fastnetmon-network
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - NET_ADMIN
      - CAP_IPC_LOCK
    secrets:
      - clickhouse_password
      - clickhouse_grafana_password
    volumes:
      - ${FNM_PATH}/services/clickhouse/custom-entrypoint.sh:/custom-entrypoint.sh:ro
      - ${FNM_PATH}/services/clickhouse/conf.d:/etc/clickhouse-server/conf.d
      - ${FNM_PATH}/seeds/clickhouse/user_files:/srv/clickhouse-user-files
      - clickhouse_data:/var/lib/clickhouse/
      - clickhouse_logs:/var/log/clickhouse-server/
    environment:
      CLICKHOUSE_USER: fastnetmon
      CLICKHOUSE_PASSWORD_FILE: /run/secrets/clickhouse_password
      GRAFANA_PASSWORD_FILE: /run/secrets/clickhouse_grafana_password
      GRAFANA_USER: grafana
    entrypoint: [ "/bin/bash", "/custom-entrypoint.sh" ]

  grafana:
    image: grafana/grafana:13.0.0-23943897787-ubuntu
    profiles:
      - visual
    container_name: grafana
    restart: unless-stopped
    networks:
      - fastnetmon-network
    user: '0'
    ports:
      - 3000:3000
    secrets:
      - grafana_admin_password
      - clickhouse_grafana_password
    environment:
      GF_PLUGINS_PREINSTALL: grafana-piechart-panel,grafana-clickhouse-datasource
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
      CLICKHOUSE_GRAFANA_HOST: clickhouse
      CLICKHOUSE_GRAFANA_USER: grafana
      CLICKHOUSE_GRAFANA_PASSWORD: ""
    volumes:
      - grafana_data:/var/lib/grafana
      - ${FNM_PATH}/services/grafana/fastnetmon.yaml:/etc/grafana/provisioning/dashboards/fastnetmon.yaml:ro
      - ${FNM_PATH}/services/grafana/fastnetmon-clickhouse.yaml:/etc/grafana/provisioning/datasources/fastnetmon-clickhouse.yaml:ro
      - ${FNM_PATH}/services/grafana/custom-run.sh:/custom-run.sh:ro
      - ${FNM_PATH}/seeds/grafana/fastnetmon_dashboards:/srv/fastnetmon_dashboards
    entrypoint: [ "/bin/bash", "/custom-run.sh" ]
