services:
  fastnetmon:
    depends_on:
      - clickhouse
    secrets:
      - clickhouse_password
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_USER: fastnetmon
      CLICKHOUSE_PASSWORD_FILE: /run/secrets/clickhouse_password
  clickhouse:
    # https://hub.docker.com/_/clickhouse
    image: clickhouse:26.3
    #container_name: fnm_clickhouse
    restart: unless-stopped
    networks:
      - fastnetmon-network
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - NET_ADMIN
      - CAP_IPC_LOCK
    secrets:
      - clickhouse_password
    volumes:
      - ${FNM_PATH}/services/clickhouse/custom-entrypoint.sh:/custom-entrypoint.sh:ro
      - ${FNM_PATH}/services/clickhouse/conf.d:/etc/clickhouse-server/conf.d
      - clickhouse_data:/var/lib/clickhouse/
      - clickhouse_logs:/var/log/clickhouse-server/
      - ${FNM_PATH}/seeds/clickhouse/user_files:/var/lib/clickhouse/user_files
    environment:
      CLICKHOUSE_USER: fastnetmon
      CLICKHOUSE_PASSWORD_FILE: /run/secrets/clickhouse_password
    entrypoint: [ "/bin/bash", "/custom-entrypoint.sh" ]
